<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<Configurations>Debug;Release</Configurations>
		<LangVersion>9</LangVersion>
		<AssemblyVersion>0.5.0</AssemblyVersion>
		<FileVersion>$(AssemblyVersion)</FileVersion>
		<Version>$(AssemblyVersion)</Version>
	</PropertyGroup>
	<Import Project="$([System.Environment]::GetEnvironmentVariable('CSII_TOOLPATH', 'EnvironmentVariableTarget.User'))\Mod.props" />
	<Import Project="$([System.Environment]::GetEnvironmentVariable('CSII_TOOLPATH', 'EnvironmentVariableTarget.User'))\Mod.targets" />
	<ItemGroup>
		<Reference Include="Colossal.Core">
			<HintPath>$(ManagedPath)\Colossal.Core.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Colossal.Mathematics">
			<HintPath>$(ManagedPath)\Colossal.Mathematics.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Colossal.Logging">
			<HintPath>$(ManagedPath)\Colossal.Logging.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Colossal.IO.AssetDatabase">
			<Private>False</Private>
		</Reference>
		<Reference Include="Colossal.Localization">
			<HintPath>$(ManagedPath)\Colossal.Localization.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Colossal.UI.Binding">
			<HintPath>$(ManagedPath)\Colossal.UI.Binding.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Game">
			<HintPath>$(ManagedPath)\Game.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Unity.Collections">
			<HintPath>$(ManagedPath)\Unity.Collections.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Unity.Entities">
			<HintPath>$(ManagedPath)\Unity.Entities.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Unity.Mathematics">
			<HintPath>$(ManagedPath)\Unity.Mathematics.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="Unity.InputSystem">
			<HintPath>$(ManagedPath)\Unity.InputSystem.dll</HintPath>
			<Private>False</Private>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>$(ManagedPath)\UnityEngine.CoreModule.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>
	<Target Name="InstallUI" AfterTargets="AfterBuild">
		<Exec Command="if not exist node_modules npm install" WorkingDirectory="$(ProjectDir)/UI" />
		<Exec Command="npm run build" WorkingDirectory="$(ProjectDir)/UI" />
	</Target>
</Project>
